[package]
name = "list-new-viewers"
version = "0.2.0"
edition = "2021"

[dependencies]
async-std = {version = "1.10.0", features = ["attributes"]}
chrono = "0.4.19"
http-types = "2.12.0"
serde = "1.0.130"
serde_json = "1.0.68"
surf = "2.3.2"
